apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      trigger:
        type: string
        default: ""
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
    needs:
      - approval
  approval:
    with:
      approvers: 015d04e8-5bcb-11eb-93be-42010a83aee8
      disallowLaunchByUser: false
      instructions: some intructions
      approvalInputs: |
        numberParam:
          type: number
          default: ""
          description: some number paraam
        stringParam:
          type: string
          default: de
    timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
