apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      tot:
        type: string
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
    needs:
      - approval-job
  approval-job:
    with:
      approvers: ""
      disallowLaunchByUser: false
      instructions: ""
      approvalInputs: |
        dddd:
          type: string
    timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
