apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      tot:
        type: string
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
    needs:
      - approval-job
  approval-job:
    with:
      approvers: ""
      disallowLaunchByUser: false
      instructions: ""
      approvalInputs: |
        dddd:
          type: string
        stringParamDef:
          type: string
          default: some defautl
          required: true
        numParam:
          type: number
          default: 1
          required: true
        boolPara:
          type: boolean
          default: false
          required: true
        choicePAram:
          type: choice
          options:
            - op1
            - op2
          default: op1
    timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
