apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "HELLO !"
          #echo "hello world ${{fromJSON(needs.approval-job.outputs.approvalInputValues).stringParam}}"
    needs:
      - approval-job
  approval-job:
    with:
      approvers: ""
      disallowLaunchByUser: false
      notifyAllEligibleUsers: false
      instructions: ""
      approvalInputs: |
        stringParam:
          type: string
          required: true
        stringParam:
          type: string
          required: true
        numberParam:
          type: number
          default: 3.9
          required: true
        boolParam:
          type: boolean
          default: false
          required: true
        choiceParam:
          type: choice
          options:
            - opt1
            - opt2
          default: ""
          required: true
        choiceParam1:
          type: choice
          default: op1
          options:
            - op1
            - op2
          description: a choice input
        choiceParam2:
          type: choice
          required: true
          options:
            - op1
            - op2
          description: a choice input          
    timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/.cloudbees/testing/custom-job.yml
