apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      stringParam:
        type: string
        default: string default
        required: true
      numberParam:
        type: number
        default: 0
        required: true
      boolParam:
        type: boolean
        default: true
        required: true
      choiceParam:
        type: choice
        options:
          - opt1
          - opt2
        default: opt2
        required: true
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
    needs:
      - approval
  approval:
    timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    with:
      approvers: 015d04e8-5bcb-11eb-93be-42010a83aee8
      disallowLaunchByUser: false
      instructions: ""
